"""Tests for Tier 3 content-authenticity checking (exemplar_retriever.py +
authenticity_checker.py + pipeline/completeness wiring).

Tier 3 catches a failure mode Tiers 1/2 and the substance gate all miss: a
long, well-written, correctly-keyworded section that clears the word-count
floor and could even answer Tier 2's yes/no checkpoints in the abstract, but
contains zero concrete data points — grounded by comparing it against a real
regulatory-document exemplar rather than judging it in isolation.

The production exemplar corpus (knowledge/exemplar_corpus.json) ships as
placeholders (no real sourced text yet), so these tests inject their own
in-memory test corpus via ExemplarRetriever's `corpus=` constructor param and
mock AuthenticityChecker.check_content_authenticity to exercise the pipeline
wiring/downgrade logic deterministically, without requiring a live Gemini key
or fabricating claims about real regulatory documents.
"""

from unittest.mock import MagicMock, patch

import numpy as np
import pytest

from app.m4_rag.authenticity_checker import AuthenticityChecker, AuthenticityResult
from app.m4_rag.completeness import CompletenessScorer
from app.m4_rag.exemplar_retriever import ExemplarRetriever
from app.m4_rag.pipeline import CTDRagCheckerPipeline
from app.m4_rag.schema import CriticalityLevel, GapItem, GapStatus, MatchEvidence, MatchMethod


@pytest.fixture(autouse=True)
def _stub_embedding_model():
    """Sections in this file exact-ID-match, and the in-memory test exemplar
    corpus below embeds via the same shared model — stub it so these tests
    stay hermetic/offline (no sentence-transformers network download)."""
    fake_model = MagicMock()
    fake_model.encode.side_effect = lambda texts, **kwargs: np.zeros((len(texts), 8))
    with patch("app.m4_rag.retriever._get_embedding_model", return_value=fake_model):
        yield


# A test-only in-memory exemplar corpus (clearly not claimed as real sourced
# text) so ExemplarRetriever.has_exemplars_for("5.3.5") is True and Tier 3
# has something to retrieve, letting the pipeline wiring under test actually
# run instead of no-op on an empty corpus.
TEST_EXEMPLAR_CORPUS = [
    {
        "section_id": "5.3.5",
        "source_citation": "TEST FIXTURE — not a real regulatory citation",
        "exemplar_text": (
            "In Study XR-204, 1,842 patients aged 40-79 were randomized 1:1 to "
            "drug or placebo; the primary endpoint (WOMAC pain subscale change "
            "at Week 12) showed a -3.4 point difference (95% CI: -4.1, -2.7; "
            "p<0.001). Serious adverse events occurred in 2.1% vs 1.8%."
        ),
    },
]


def _make_exemplar_retriever() -> ExemplarRetriever:
    return ExemplarRetriever(corpus=TEST_EXEMPLAR_CORPUS)


GENERIC_CANDIDATE_TEXT = (
    "This report presents the clinical study results supporting the efficacy "
    "and safety of the product in the intended patient population. The study "
    "was designed in accordance with applicable regulatory guidance and was "
    "conducted at multiple qualified clinical sites by experienced "
    "investigators. Patients meeting the protocol-specified criteria were "
    "enrolled and treated according to the approved study design, with "
    "appropriate oversight from the sponsor and the independent monitoring "
    "committee throughout the conduct of the trial. Efficacy was assessed "
    "using validated and clinically meaningful measures, and the results "
    "demonstrate a favorable outcome consistent with the therapeutic goals "
    "of the program. Safety was carefully monitored throughout the study "
    "period, with adverse events collected, reviewed, and reported in "
    "accordance with standard pharmacovigilance practice. The overall "
    "benefit-risk profile observed in this study supports the continued "
    "development and potential approval of the product for the proposed "
    "indication. Investigators and site staff received appropriate training "
    "prior to study initiation, and data management procedures followed "
    "industry-standard practices to ensure data integrity and quality "
    "throughout the trial. The sponsor remains confident in the strength of "
    "the totality of evidence generated by this well-conducted clinical "
    "program and believes it adequately characterizes the product's "
    "efficacy and safety for the target population under study."
) * 3  # comfortably clears the 500-word Module 5 CRITICAL substance-gate floor


SUBSTANTIVE_CANDIDATE_TEXT = (
    "This report presents the pivotal Phase 3, randomized, double-blind, "
    "placebo-controlled trial of rofecoxib in 2,756 adult and geriatric "
    "patients aged 18 to 85 with osteoarthritis of the knee or hip, "
    "conducted at 94 centers across North America and Europe. The primary "
    "efficacy endpoint was the mean change from baseline in the WOMAC pain "
    "subscale at Week 12, which showed a statistically significant "
    "improvement of -3.8 points (95% CI: -4.5, -3.1; p<0.001) versus "
    "placebo. Patient disposition showed 2,412 patients completed the "
    "12-week treatment period. Serious adverse events, including three "
    "cardiovascular thrombotic events, were adjudicated by an independent "
    "safety committee and are tabulated alongside gastrointestinal "
    "perforation, ulceration, and bleeding rates observed in 1.4% of "
    "rofecoxib-treated patients versus 2.9% of the ibuprofen comparator arm."
) * 5  # ~600 words, comfortably clears the 500-word Module 5 CRITICAL substance-gate floor


def _run_pipeline_for_section(
    section_body_text: str,
    mocked_verdict: str,
    missing_data_points=None,
):
    pipeline = CTDRagCheckerPipeline(exemplar_retriever=_make_exemplar_retriever())

    fake_result = AuthenticityResult(
        verdict=mocked_verdict,
        missing_data_points=missing_data_points or [],
        candidate_citation=None,
        exemplar_citations=["TEST FIXTURE excerpt"],
        reasoning=f"Mocked {mocked_verdict} verdict for wiring test.",
    )

    with patch.object(
        AuthenticityChecker, "check_content_authenticity", return_value=fake_result
    ) as mock_check:
        report = pipeline.run(
            {
                "submission_title": "Tier 3 Authenticity Wiring Test",
                "drug_name": "VIOXX",
                "sections": [
                    {
                        "section_id": "5.3.5",
                        "title": "Reports of Efficacy and Safety Studies",
                        "body_text": section_body_text,
                    },
                ],
            },
            enable_reasoner=False,
        )

    item = next(
        g
        for g in report.present_sections + report.partial_sections + report.missing_sections
        if g.section_id == "5.3.5"
    )
    return report, item, mock_check


# ─── GENERIC candidate: downgrades even though it clears substance gate ───


def test_generic_candidate_downgrades_to_partial_effective_status():
    report, item, mock_check = _run_pipeline_for_section(
        GENERIC_CANDIDATE_TEXT,
        mocked_verdict="GENERIC",
        missing_data_points=["sample size", "p-value", "named study identifier"],
    )

    # Confirm Tier 3 actually ran (exemplars were found and the checker was invoked).
    assert mock_check.called

    # Passed the substance gate (word count clears the floor) and Tier 1
    # matched it structurally — without Tier 3, this would be PRESENT.
    assert item.substance_gate_reason is None
    assert item.status == GapStatus.PRESENT

    # Tier 3 verdict recorded with its evidence.
    assert item.authenticity_verdict == "GENERIC"
    assert item.authenticity_evidence is not None
    assert "sample size" in item.authenticity_evidence["missing_data_points"]
    assert item.authenticity_evidence["source_citations"] == ["TEST FIXTURE — not a real regulatory citation"]

    # The effective score used in the weighted formula is downgraded to
    # PARTIAL (0.5) despite Tier 1 saying PRESENT.
    scorer = CompletenessScorer()
    assert scorer._effective_status_score(item) == CompletenessScorer.WEIGHT_PARTIAL


def test_insufficient_verdict_downgrades_to_missing_effective_status():
    report, item, mock_check = _run_pipeline_for_section(
        GENERIC_CANDIDATE_TEXT,
        mocked_verdict="INSUFFICIENT",
        missing_data_points=["everything concrete"],
    )
    assert mock_check.called
    assert item.authenticity_verdict == "INSUFFICIENT"

    scorer = CompletenessScorer()
    assert scorer._effective_status_score(item) == CompletenessScorer.WEIGHT_MISSING
    # With this section forced to an effective 0.0 and every other KB
    # requirement genuinely MISSING (a single-section dossier), the overall
    # weighted score has nothing earning any points at all.
    assert report.overall_completeness == 0.0


# ─── Critical false-positive guard: genuinely substantive content ─────────


def test_substantive_verdict_does_not_downgrade_real_content():
    report, item, mock_check = _run_pipeline_for_section(
        SUBSTANTIVE_CANDIDATE_TEXT,
        mocked_verdict="SUBSTANTIVE",
        missing_data_points=[],
    )
    assert mock_check.called
    assert item.authenticity_verdict == "SUBSTANTIVE"
    assert item.status == GapStatus.PRESENT

    # SUBSTANTIVE leaves the prior tier's effective status unchanged — still
    # counts as fully PRESENT for scoring.
    scorer = CompletenessScorer()
    assert scorer._effective_status_score(item) == CompletenessScorer.WEIGHT_PRESENT


def test_downgrade_ordering_end_to_end():
    """A single, direct end-to-end comparison: for the identical candidate
    text and exemplar, only the mocked verdict changes — overall readiness
    must strictly decrease as the verdict worsens."""
    report_substantive, _, _ = _run_pipeline_for_section(SUBSTANTIVE_CANDIDATE_TEXT, "SUBSTANTIVE")
    report_generic, _, _ = _run_pipeline_for_section(SUBSTANTIVE_CANDIDATE_TEXT, "GENERIC")
    report_insufficient, _, _ = _run_pipeline_for_section(SUBSTANTIVE_CANDIDATE_TEXT, "INSUFFICIENT")

    assert (
        report_substantive.overall_completeness
        > report_generic.overall_completeness
        > report_insufficient.overall_completeness
        == 0.0
    )


# ─── Gating conditions: Tier 3 must not run outside its intended scope ────


def test_tier3_skips_sections_forced_missing_by_substance_gate():
    """A section with almost no body_text is forced MISSING by the substance
    gate before Tier 3 ever gets a chance to run — even with exemplars
    available and the checker mocked to return a verdict, it must not fire."""
    pipeline = CTDRagCheckerPipeline(exemplar_retriever=_make_exemplar_retriever())
    fake_result = AuthenticityResult(
        verdict="SUBSTANTIVE", missing_data_points=[], candidate_citation=None,
        exemplar_citations=[], reasoning="should never be reached",
    )

    with patch.object(
        AuthenticityChecker, "check_content_authenticity", return_value=fake_result
    ) as mock_check:
        report = pipeline.run(
            {
                "submission_title": "Thin Section Test",
                "sections": [
                    {"section_id": "5.3.5", "title": "CSR", "body_text": "Only a few words here."},
                ],
            },
            enable_reasoner=False,
        )

    mock_check.assert_not_called()
    item = next(g for g in report.missing_sections if g.section_id == "5.3.5")
    assert item.substance_gate_reason is not None
    assert item.authenticity_verdict is None


def test_tier3_skips_when_no_exemplars_for_section():
    """With the production-shipped placeholder corpus (no real exemplars for
    any section), Tier 3 must no-op entirely, even for a section that
    otherwise passes the substance gate — this is the "empty corpus degrades
    cleanly" contract."""
    pipeline = CTDRagCheckerPipeline()  # default ExemplarRetriever loads the real (placeholder) corpus
    assert pipeline.exemplar_retriever.is_available is False

    with patch.object(AuthenticityChecker, "check_content_authenticity") as mock_check:
        report = pipeline.run(
            {
                "submission_title": "Placeholder Corpus Test",
                "sections": [
                    {
                        "section_id": "5.3.5",
                        "title": "Reports of Efficacy and Safety Studies",
                        "body_text": SUBSTANTIVE_CANDIDATE_TEXT,
                    },
                ],
            },
            enable_reasoner=False,
        )

    mock_check.assert_not_called()
    item = next(g for g in report.present_sections + report.partial_sections if g.section_id == "5.3.5")
    assert item.authenticity_verdict is None
    assert item.authenticity_evidence is None


def test_tier3_skips_sections_without_body_text():
    """Structured/API dossiers that never set body_text (the vast majority
    of existing demo/test dossiers) must never trigger Tier 3, even when
    exemplars exist for that section_id."""
    pipeline = CTDRagCheckerPipeline(exemplar_retriever=_make_exemplar_retriever())

    with patch.object(AuthenticityChecker, "check_content_authenticity") as mock_check:
        report = pipeline.run(
            {
                "submission_title": "No Body Text Test",
                "sections": [
                    {
                        "section_id": "5.3.5",
                        "title": "Reports of Efficacy and Safety Studies",
                        "description": "Pivotal Phase 3 osteoarthritis and acute pain clinical study reports.",
                    },
                ],
            },
            enable_reasoner=False,
        )

    mock_check.assert_not_called()
    item = next(g for g in report.present_sections + report.partial_sections if g.section_id == "5.3.5")
    assert item.authenticity_verdict is None


# ─── ExemplarRetriever unit tests ──────────────────────────────────────────


def test_exemplar_retriever_empty_corpus_is_unavailable():
    retriever = ExemplarRetriever(corpus=[])
    assert retriever.is_available is False
    assert retriever.has_exemplars_for("5.3.5") is False
    assert retriever.retrieve("5.3.5", "some candidate text") == []


def test_exemplar_retriever_drops_placeholder_records():
    retriever = ExemplarRetriever(corpus=[
        {"section_id": "5.3.5", "source_citation": "TODO", "exemplar_text": ""},
    ])
    assert retriever.is_available is False


def test_exemplar_retriever_scopes_to_exact_section_id():
    retriever = _make_exemplar_retriever()
    assert retriever.has_exemplars_for("5.3.5") is True
    assert retriever.has_exemplars_for("4.2.3") is False
    results = retriever.retrieve("5.3.5", "candidate text", top_k=2)
    assert len(results) == 1
    assert results[0].section_id == "5.3.5"


# ─── AuthenticityChecker unit tests ────────────────────────────────────────


def test_authenticity_checker_skips_without_exemplars():
    checker = AuthenticityChecker(api_key="fake-key")
    result = checker.check_content_authenticity(
        candidate_section={"section_id": "5.3.5", "title": "CSR", "text": "some text"},
        exemplars=[],
    )
    assert result is None


def test_authenticity_checker_skips_without_api_key():
    checker = AuthenticityChecker(api_key="")
    assert not checker.is_available
    result = checker.check_content_authenticity(
        candidate_section={"section_id": "5.3.5", "title": "CSR", "text": "some text"},
        exemplars=[{"source_citation": "x", "exemplar_text": "y"}],
    )
    assert result is None
